### ISSUE TITLE
Ensure TRUE/FALSE is caught when validating sample-sheets.

### ISSUE THREAD

**Issue by charles-cowart** [biocore/metagenomics_pooling_notebook#188]
Sample-sheets must now use 'True' or 'False' explicitly. Ensure validation catches this so that processing doesn't begin before this error is caught (ValueError: 'TRUE' is not a valid value for BarcodesAreRC).

**Comment by ackermag** [comment]
This is a real problem for people generating the sample_sheets who want to check that they are correctly formatted because the default viewer is Excel.  Excel will automatically convert any version of true and false to TRUE and FALSE with central justification in the cell.  In order to correct this, the SRA/processor of data needs to remember to convert to 'True' and 'False'.  Why can't the code accept any version of true and false.

**Comment by charles-cowart** [comment]
> This is a real problem for people generating the sample_sheets who want to check that they are correctly formatted because the default viewer is Excel. Excel will automatically convert any version of true and false to TRUE and FALSE with central justification in the cell. In order to correct this, the SRA/processor of data needs to remember to convert to 'True' and 'False'. Why can't the code accept any version of true and false.

We used to be able to do this, but Daniel and Rob asked that I remove it. @wasade, I've been getting frequent requests to let True and False be case in-sensitive. If someone uses Excel to make a manual correction in a sample-sheet, it will instantly become invalid because Excel implicitly converts all forms of true and false to TRUE and FALSE. Would you mind if this made a comeback?

**Comment by charles-cowart** [comment]
Resolved with https://github.com/charles-cowart/metagenomics_pooling_notebook/tree/bool_case_fix
