### ISSUE TITLE
add drop_zeros attribute to read_visionmate_file() to drop leading zeros. 

### ISSUE THREAD

**Issue by RodolfoSalido** [biocore/metagenomics_pooling_notebook#241]
https://github.com/biocore/metagenomics_pooling_notebook/blob/ff2260e2db8584f654c199a8a8b993f8dfb74dae/metapool/metapool.py#L1623

Feature to drop leading zeros from vision mate files.

**Comment by AmandaBirmingham** [comment]
@RodolfoSalido I take it that the VisionMate is the only instrument that is providing leading zeroes?  Or is it just the only one whose output is used in the notebooks?  I am pondering whether this modification should go into the visionmate-specific code or should maybe go up a level in `compress_plates`, perhaps right before the merge with the sample accession info; my thinking is that if in the future we swap or augment the visionmate with another instrument, it would be good if we didn't have to remember to build this clean-up step into that instrument's new parsing function as well.

**Comment by charles-cowart** [comment]
I believe it is. Do you know @mmbryant23 ?

**Comment by RodolfoSalido** [comment]
The VisionMate and a hand scanner that feeds google spreadsheets are the only instruments that we use to read matrix tube barcodes. 

I think add_controls() and validate_plate_df() also call for the read_visionmate_file() helper function. That's why I thought that targetting the read_visionmate_file() function was somewhat efficient. 

However, I agree that maybe the leading zero dropping should be incorporated into the compress_plates() function as well, so that there are no discrepancies between the sample_accesion TubeCodes and the VisioMate files' TubeCodes. 

I guess maybe this drop_zeros feature request should be analyzed and discussed more thoroughly.

**Comment by AmandaBirmingham** [comment]
> I think add_controls() and validate_plate_df() also call for the read_visionmate_file() helper function.

Ooo, good point! I actually think it should NOT be called in so many places; for example, in `add_controls`, it is called twice within 13 lines (see below), whereas we should probably just load the data into a dataframe once and use it.  That said, that sort of refactor is more long-term.  

How about we compromise on putting the zero-stripping code into a small function (even though it is probably just a line or two) that is called from `read_visionmate_file` , so that if we *do* need to strip zeroes at other points we can call it and guarantee we will be doing zero-stripping in the same everywhere?

https://github.com/biocore/metagenomics_pooling_notebook/blob/ff2260e2db8584f654c199a8a8b993f8dfb74dae/metapool/metapool.py#L1799-L1812
