### ISSUE TITLE
OverrideCycles is invalid for iSeq

### ISSUE THREAD

**Issue by wasade** [biocore/metagenomics_pooling_notebook#67]
This [entry](https://github.com/biocore/metagenomics_pooling_notebook/blob/826feddeb5cdf538e357cfd0980d25b203078b4e/metapool/sample_sheet.py#L62) specifically. It should not be included in the output sheet if the instrument is the iSeq

**Comment by charles-cowart** [comment]
@wasade Just to confirm, https://github.com/biocore/metagenomics_pooling_notebook/blob/826feddeb5cdf538e357cfd0980d25b203078b4e/metapool/sample_sheet.py#L61 (MaskShortReads) is still a positive addition?

**Comment by wasade** [comment]
I'm not sure, sorry. It was problematic when we were rapidly trying to process an iSeq run but I don't have more information. Jeff (forgot his handle) or @antgonza, do you know?

**Comment by antgonza** [comment]
Both need to be removed when using iSeq.

**Comment by charles-cowart** [comment]
Thanks guys. It seems like the definitive way to determine if the run was an iSeq run is to examine the run-id. However this info isn't usually given in the sample-sheet or the prep-sheet. Do you guys know of an alternative? Otherwise it seems like I might have to force the user to supply a run-id or isIseq parameter at KLSampleSheet creation time.

**Comment by RodolfoSalido** [comment]
We specify the sequencing platform during KLSampleSheet creation time.

**Comment by charles-cowart** [comment]
@RodolfoSalido Ah thank you! I did not notice sequencer was added as a parameter to make_sample_sheet(). I'll add it to the docstring.

**Comment by antgonza** [comment]
Fixed here: https://github.com/biocore/metagenomics_pooling_notebook/pull/71
